# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d542300de1ed5a3d9b8299e1e39869a3"
name = "pasimistic-plant"
handle = "pasimistic-plant"
application_url = "https://read-commissioner-please-mardi.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "healthyhomebd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://read-commissioner-please-mardi.trycloudflare.com/auth/callback",
  "https://read-commissioner-please-mardi.trycloudflare.com/auth/shopify/callback",
  "https://read-commissioner-please-mardi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
